/* automatically generated by rust-bindgen */

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct StarRef {
    _unused: [u8; 0],
}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Aligner {
    _unused: [u8; 0],
}
extern "C" {
    pub fn align_read(
        arg1: *mut Aligner,
        arg2: *const ::std::os::raw::c_char,
    ) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn align_read_pair(
        arg1: *mut Aligner,
        arg2: *const ::std::os::raw::c_char,
        arg3: *const ::std::os::raw::c_char,
    ) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn init_star_ref(
        arg1: ::std::os::raw::c_int,
        arg2: *const *const ::std::os::raw::c_char,
    ) -> *const StarRef;
}
extern "C" {
    pub fn init_aligner_from_ref(arg1: *const StarRef) -> *mut Aligner;
}
extern "C" {
    pub fn destroy_aligner(arg1: *mut Aligner);
}
extern "C" {
    pub fn destroy_ref(arg1: *const StarRef);
}
