name: Test

on:
  pull_request:
  push:
    branches:
      - master

env:
  CARGO_DENY_VERSION: 0.12.2
  RUST_VERSION: 1.63.0

jobs:
  rust:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout git repository
        uses: actions/checkout@master
      - name: Checkout git submodules
        run: git submodule update --init --depth=1
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v1
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{env.RUST_VERSION}}
          components: rustfmt, clippy
          default: true
      - name: Install cargo-deny
        run: |
          mkdir -p ~/bin/
          curl -L "https://github.com/EmbarkStudios/cargo-deny/releases/download/${CARGO_DENY_VERSION}/cargo-deny-${CARGO_DENY_VERSION}-x86_64-unknown-linux-musl.tar.gz" \
            | tar -xz -C ~/bin/ --strip-components=1 "cargo-deny-${CARGO_DENY_VERSION}-x86_64-unknown-linux-musl/cargo-deny"
          echo "$HOME/bin" >> "$GITHUB_PATH"
      - name: Check Rust formatting
        run: cargo fmt -- --check
      - name: Remove the Cargo target directory
        if: github.ref == 'refs/heads/master'
        run: cargo clean
      - name: Check dependency licenses
        run: cargo deny --locked check
      - name: Run clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          args: |
            --all-targets --locked --
            -D clippy::perf
            -D clippy::style
            -D clippy::suspicious
            -A clippy::comparison_chain
            -W future_incompatible
            -W nonstandard_style
            -W rust_2021_compatibility
            -W unused
            -D clippy::enum_glob_use
            -D clippy::redundant_closure_for_method_calls
            -D clippy::unnecessary_unwrap
            -D clippy::unused_io_amount
            -D clippy::wildcard_imports
            -D clippy::blacklisted_name
      - name: Run Rust tests
        run: RUST_BACKTRACE=1 cargo test --locked
