name: Test

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  rust:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout git repository
        uses: actions/checkout@master
      - name: Checkout git submodules
        run: git submodule update --init --depth=1
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v1
      - name: Check Rust formatting
        run: cargo fmt -- --check
      - name: Remove the Cargo target directory
        if: github.ref == 'refs/heads/master'
        run: cargo clean
      - name: Run Rust tests
        run: RUST_BACKTRACE=1 cargo test --locked
